"use client";

import { Filter, ArrowUpDown, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import Link from "next/link";

const brand = "#0d5c52";

const SAMPLE_ROWS = [
  {
    agent: "bill@motormouth.io",
    address: "4500 N Ocean Dr, Singer Island, FL",
    date: "Apr 8, 2026",
  },
  {
    agent: "bill@motormouth.io",
    address: "48 S Main St, Salt Lake City, UT",
    date: "Apr 2, 2026",
  },
];

export default function SampleManageReports() {
  return (
    <div className="max-w-6xl mx-auto">
      <h1 className="text-2xl font-semibold tracking-tight text-zinc-900">
        Manage Your Reports
      </h1>

      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <div className="h-28 rounded-2xl border border-zinc-200 bg-zinc-100/80" aria-hidden />
        <div className="h-28 rounded-2xl border border-zinc-200 bg-zinc-100/80" aria-hidden />
      </div>

      <div className="mt-10 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <h2 className="text-lg font-semibold text-zinc-900">Your Generated Reports</h2>
          <p className="text-sm text-zinc-600 mt-1">
            A list of all the reports you have generated.
          </p>
        </div>
        <div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center">
          <label className="sr-only" htmlFor="report-search">
            Search reports
          </label>
          <input
            id="report-search"
            type="search"
            placeholder="Search reports..."
            className="h-9 w-full min-w-[12rem] rounded-xl border border-zinc-200 bg-white px-3 text-sm shadow-sm outline-none focus-visible:ring-2 focus-visible:ring-[#0d5c52]/25 sm:w-56"
          />
          <Button
            variant="outline"
            className="h-9 rounded-xl border-zinc-200 gap-2 w-full sm:w-auto"
          >
            <Filter className="opacity-70" aria-hidden /> Filters
          </Button>
          <Button className="h-9 rounded-xl bg-[#0d5c52] hover:bg-[#0a4a42] text-white w-full sm:w-auto shadow-sm">
            Generate Custom Report
          </Button>
        </div>
      </div>

      <div className="mt-6 rounded-2xl border border-zinc-200 bg-white shadow-sm overflow-hidden">
        <Table className="min-w-[600px]">
          <TableHeader>
            <TableRow className="hover:bg-transparent">
              <TableHead className="text-zinc-700">
                <button type="button" className="inline-flex items-center gap-1 font-medium">
                  Generated By Agent
                  <ArrowUpDown className="size-3.5 opacity-45" aria-hidden />
                </button>
              </TableHead>
              <TableHead className="text-zinc-700">
                <button type="button" className="inline-flex items-center gap-1 font-medium">
                  Address
                  <ArrowUpDown className="size-3.5 opacity-45" aria-hidden />
                </button>
              </TableHead>
              <TableHead className="text-zinc-700">
                <button type="button" className="inline-flex items-center gap-1 font-medium">
                  Date Generated
                  <ArrowUpDown className="size-3.5 opacity-45" aria-hidden />
                </button>
              </TableHead>
              <TableHead className="w-px text-zinc-700 text-right pr-6">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {SAMPLE_ROWS.map((row, i) => (
              <TableRow key={i}>
                <TableCell className="font-medium text-zinc-900">{row.agent}</TableCell>
                <TableCell className="max-w-[16rem] whitespace-normal text-zinc-700">
                  {row.address}
                </TableCell>
                <TableCell className="text-zinc-600">{row.date}</TableCell>
                <TableCell className="text-right pr-6">
                  <div className="inline-flex items-center gap-4">
                    <Link
                      href="#"
                      onClick={(e) => e.preventDefault()}
                      className="text-sm font-medium hover:underline"
                      style={{ color: brand }}
                    >
                      View Report
                    </Link>
                    <button
                      type="button"
                      className="rounded-lg p-1.5 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-600"
                      aria-label="Delete report"
                    >
                      <Trash2 className="size-4" />
                    </button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
